### ISSUE TITLE
FastForwardReporter reports metered stats for timers with unit ns/s

### ISSUE THREAD

**Issue by jo-ri** [spotify/semantic-metrics#11]
For each Timer, FastForwardReporter will report the histogram stats with unit ns which is correct, but also the metered stats 1m and 5m with the unit ns/s which is not.

See: https://github.com/spotify/semantic-metrics/blob/master/ffwd-reporter/src/main/java/com/spotify/metrics/ffwd/FastForwardReporter.java#L284

If the metered stats should be reported for timers, they should have a proper unit. A reason to omit reporting metered stats for timers is that it makes it possible to define the MetricId more precisely.

**Comment by mattnworb** [comment]
I find it incredibly useful to have the 1m/5m etc stats for each Timer automatically reported, so I hope that isn't removed. Otherwise I would end up using a Meter and a Timer next to each other in my application code in most places where I use just a Timer today.

What would be a better unit for those stats? `events/s`?

**Comment by jo-ri** [comment]
Yes, I think `events/s`, `samples/s` or something like that would be fine, or something configured by the user (e.g. requests/s or writes/s).

I agree it is useful that a Timer collects both a histogram of durations and a metered value, I just thought it could be useful to report them with separate MetricIds since they represent quite different things.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
